/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuconeventos;

import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class VentanaConEventos extends javax.swing.JFrame {

  /**
   * Creates new form VentanaConEventos
   */
  public VentanaConEventos() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelDibujo1 = new poligonoconeventos.PanelDibujo();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    opcionAbrir = new javax.swing.JMenuItem();
    separador = new javax.swing.JPopupMenu.Separator();
    opcionSalir = new javax.swing.JMenuItem();
    menuAyuda = new javax.swing.JMenu();
    opcionAcercaDe = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Ventana Con Eventos");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    javax.swing.GroupLayout panelDibujo1Layout = new javax.swing.GroupLayout(panelDibujo1);
    panelDibujo1.setLayout(panelDibujo1Layout);
    panelDibujo1Layout.setHorizontalGroup(
      panelDibujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    panelDibujo1Layout.setVerticalGroup(
      panelDibujo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 276, Short.MAX_VALUE)
    );

    getContentPane().add(panelDibujo1, java.awt.BorderLayout.CENTER);

    menuArchivo.setText("Archivo");

    opcionAbrir.setText("Abrir");
    menuArchivo.add(opcionAbrir);
    menuArchivo.add(separador);

    opcionSalir.setText("Salir");
    opcionSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        opcionSalirActionPerformed(evt);
      }
    });
    menuArchivo.add(opcionSalir);

    barraMenu.add(menuArchivo);

    menuAyuda.setText("Ayuda");

    opcionAcercaDe.setText("Acerca de");
    menuAyuda.add(opcionAcercaDe);

    barraMenu.add(menuAyuda);

    setJMenuBar(barraMenu);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    // TODO add your handling code here:
    salirDelPrograma();
  }//GEN-LAST:event_formWindowClosing

  private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
    // TODO add your handling code here:
    salirDelPrograma();
  }//GEN-LAST:event_opcionSalirActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuAyuda;
  private javax.swing.JMenuItem opcionAbrir;
  private javax.swing.JMenuItem opcionAcercaDe;
  private javax.swing.JMenuItem opcionSalir;
  private poligonoconeventos.PanelDibujo panelDibujo1;
  private javax.swing.JPopupMenu.Separator separador;
  // End of variables declaration//GEN-END:variables

  private void salirDelPrograma() {
    int opcion = JOptionPane.showConfirmDialog(this,"¿Salir del programa?","Confirmación",JOptionPane.OK_CANCEL_OPTION);
    if(opcion==JOptionPane.OK_OPTION){
      System.exit(0);
    }
  }
}
