/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneleventoboton;

/**
 *
 * @author tahil
 */
public class PanelEventoBoton extends javax.swing.JPanel {

  /**
   * Creates new form PanelEventoBoton
   */
  public PanelEventoBoton() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    botonAzul = new javax.swing.JButton();
    BotonVerde = new javax.swing.JButton();

    botonAzul.setText("Cambiar fondo a Azul");
    botonAzul.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonAzulActionPerformed(evt);
      }
    });
    add(botonAzul);

    BotonVerde.setText("Cambiar fondo a Verde");
    BotonVerde.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonVerdeActionPerformed(evt);
      }
    });
    add(BotonVerde);
  }// </editor-fold>//GEN-END:initComponents

  private void botonAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAzulActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonAzulActionPerformed

  private void BotonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerdeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_BotonVerdeActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BotonVerde;
  private javax.swing.JButton botonAzul;
  // End of variables declaration//GEN-END:variables
}
