/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package examen2;

import java.awt.Graphics;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelConMalla extends javax.swing.JPanel {

  private int filas;
  private int columnas;

  /**
   * Creates new form PanelMalla
   */
  public PanelConMalla() {
    initComponents();
  }

  @Override
  public void paintComponent(Graphics g) {
    super.paintComponent(g);
    dibujar(g);
  }

  public void dibujar(Graphics g) {
    if (filas!=0 && columnas!=0) {
      int dx = getWidth() / columnas;
      for (int i = 0; i < columnas; i++) {
        g.drawLine(i * dx, 0, i * dx, getHeight());
      }
      int dy = getHeight() / filas;
      for (int i = 0; i < filas; i++) {
        g.drawLine(0, i * dy, getWidth(), i * dy);
      }
    }
  }

  public void setFilas(int filas) {
    this.filas = filas;
  }

  public void setColumnas(int columnas) {
    this.columnas = columnas;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
