/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class VentanaMalla extends javax.swing.JFrame {

  /**
   * Creates new form VentanaMalla
   */
  public VentanaMalla() {
    initComponents();
  }
  
  public void addEventos(OyenteMenu oyente){
    this.opcionAbrir.addActionListener(oyente);
    this.opcionSalir.addActionListener(oyente);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    barraMenu = new javax.swing.JMenuBar();
    menuSalir = new javax.swing.JMenu();
    opcionAbrir = new javax.swing.JMenuItem();
    separadorArchivo = new javax.swing.JPopupMenu.Separator();
    opcionSalir = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Malla");

    menuSalir.setText("Archivo");

    opcionAbrir.setText("Abrir");
    opcionAbrir.setName("abrir"); // NOI18N
    menuSalir.add(opcionAbrir);
    menuSalir.add(separadorArchivo);

    opcionSalir.setText("Salir");
    opcionSalir.setName("salir"); // NOI18N
    menuSalir.add(opcionSalir);

    barraMenu.add(menuSalir);

    setJMenuBar(barraMenu);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JMenu menuSalir;
  private javax.swing.JMenuItem opcionAbrir;
  private javax.swing.JMenuItem opcionSalir;
  private javax.swing.JPopupMenu.Separator separadorArchivo;
  // End of variables declaration//GEN-END:variables
}
