/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen3;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import poligonoconeventos.PanelDibujo;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class VentanaPoligono extends javax.swing.JFrame {

  /**
   * Creates new form VentanaPoligono
   */
  public VentanaPoligono() {
    initComponents();
    
  }
  
  public void addEventos(OyenteVentana oyente){
    this.botonAumentar.addActionListener(oyente);
    this.botonDisminuir.addActionListener(oyente);
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    botonAumentar = new javax.swing.JButton();
    botonDisminuir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    botonAumentar.setText("Aumentar");
    jPanel1.add(botonAumentar);

    botonDisminuir.setText("Disminuir");
    jPanel1.add(botonDisminuir);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonAumentar;
  private javax.swing.JButton botonDisminuir;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
