/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package eventoboton;
/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelEventoBoton extends javax.swing.JPanel {

    /**
     * Creates new form PanelEventoBoton
     */
    public PanelEventoBoton() {
        initComponents();
    }

    public void addEventos(OyenteEventoBoton oyente) {
        botonAzul.addActionListener(oyente);
        botonVerde.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAzul = new javax.swing.JButton();
        botonVerde = new javax.swing.JButton();

        botonAzul.setText("Cambiar fondo a azul");
        botonAzul.setName("azul"); // NOI18N
        add(botonAzul);

        botonVerde.setText("Cambiar fondo a Verde");
        botonVerde.setName("verde"); // NOI18N
        add(botonVerde);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAzul;
    private javax.swing.JButton botonVerde;
    // End of variables declaration//GEN-END:variables
}
