/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package editor;

import java.net.URL;
import java.util.ArrayList;
import util.Archivo;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelEditor extends javax.swing.JPanel {

  /**
   * Creates new form PanelEditor
   */
  public PanelEditor() {
    initComponents();
    abrirArchivo();
  }
  
  public void abrirArchivo(){
    //Abrir el archivo de texto y cargarlo al objeto areaEditor
    String archivo = "/archivos/HimnoITV.txt";
    URL url = this.getClass().getResource(archivo);
    System.out.println(url.getPath());
    ArrayList<String> contenido = Archivo.leerArchivo(url.getPath());
    for(int i=0;i<contenido.size();i++){
      System.out.println(contenido.get(i));
    }
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    panelCentro = new javax.swing.JTextArea();

    setLayout(new java.awt.BorderLayout());

    jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

    panelCentro.setColumns(20);
    panelCentro.setFont(new java.awt.Font("JetBrains Mono", 0, 20)); // NOI18N
    panelCentro.setRows(5);
    panelCentro.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
    jScrollPane1.setViewportView(panelCentro);

    add(jScrollPane1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea panelCentro;
  // End of variables declaration//GEN-END:variables
}
