/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chat;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelChat extends javax.swing.JPanel {

  /**
   * Creates new form PanelChat
   */
  public PanelChat() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    etiquetaChat = new javax.swing.JLabel();
    campoChat = new javax.swing.JTextField();

    setLayout(new java.awt.BorderLayout());

    etiquetaChat.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
    etiquetaChat.setText("Captura un mensaje:");
    panelNorte.add(etiquetaChat);

    campoChat.setColumns(30);
    panelNorte.add(campoChat);

    add(panelNorte, java.awt.BorderLayout.PAGE_START);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField campoChat;
  private javax.swing.JLabel etiquetaChat;
  private javax.swing.JPanel panelNorte;
  // End of variables declaration//GEN-END:variables
}
