/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package controljugadores;

import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class DialogoRegistroJugador extends javax.swing.JDialog {

  /**
   * Creates new form DialogoRegistroJugador
   */
  public DialogoRegistroJugador(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setSize(400,300);
    
  }

  public JButton getBotonAceptar(){
    return this.botonAceptar;
  }
  
  public void addEventos(OyenteJugadores oyente){
    botonAceptar.addActionListener(oyente);
    botonCancelar.addActionListener(oyente);
    addWindowListener(oyente);
    botonAceptar.setName("aceptar");
    botonCancelar.setName("cancelar");
    setName("dialogo");
  }
  
  public void show(String titulo,String textoBoton,boolean estadoNombre,boolean estadoCombos){
    setTitle(titulo);
    botonAceptar.setText(textoBoton);
    campoNombre.setEnabled(estadoNombre);
    comboPronostico.setEnabled(estadoCombos);
    comboTemperatura.setEnabled(estadoCombos);
    comboHumedad.setEnabled(estadoCombos);
    comboViento.setEnabled(estadoCombos);
    comboJugar.setEnabled(estadoCombos);
    JFrame padre = (JFrame)getParent();
    int x = padre.getX()+padre.getWidth()/2-getWidth()/2;
    int y = padre.getY()+padre.getHeight()/2-getHeight()/2;
    setLocation(x,y);
    setVisible(true);
  }
  
  public void setComponentes(String[] valores){
    this.campoNombre.setText(valores[0]);
    this.comboPronostico.setSelectedItem(valores[1]);
    this.comboTemperatura.setSelectedItem(valores[2]);
    this.comboHumedad.setSelectedItem(valores[3]);
    this.comboViento.setSelectedItem(valores[4]);
    this.comboJugar.setSelectedItem(valores[5]);
  }
  
  public String[] getCOmponentes(){
    return new String[]{
      this.campoNombre.getText(),
      (String)this.comboPronostico.getSelectedItem(),
      (String)this.comboTemperatura.getSelectedItem(),
      (String)this.comboHumedad.getSelectedItem(),
      (String)this.comboViento.getSelectedItem(),
      (String)this.comboJugar.getSelectedItem()
    };
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    etiquetaNombre = new javax.swing.JLabel();
    campoNombre = new javax.swing.JTextField();
    panelCentro = new javax.swing.JPanel();
    etiquetaPronostico = new javax.swing.JLabel();
    comboPronostico = new javax.swing.JComboBox<>();
    etiquetaTemperatura = new javax.swing.JLabel();
    comboTemperatura = new javax.swing.JComboBox<>();
    etiquetaHumedad = new javax.swing.JLabel();
    comboHumedad = new javax.swing.JComboBox<>();
    etiquetaViento = new javax.swing.JLabel();
    comboViento = new javax.swing.JComboBox<>();
    etiquetaJugar = new javax.swing.JLabel();
    comboJugar = new javax.swing.JComboBox<>();
    panelSur = new javax.swing.JPanel();
    botonAceptar = new javax.swing.JButton();
    botonCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Jugador");

    panelNorte.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del jugador:"));

    etiquetaNombre.setText("Nombre del jugador:");
    panelNorte.add(etiquetaNombre);

    campoNombre.setColumns(15);
    panelNorte.add(campoNombre);

    getContentPane().add(panelNorte, java.awt.BorderLayout.NORTH);

    panelCentro.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado del tiempo:"));
    panelCentro.setLayout(new java.awt.GridLayout(5, 2));

    etiquetaPronostico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaPronostico.setText("Pronóstico :");
    panelCentro.add(etiquetaPronostico);

    comboPronostico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soleado", "Nublado", "Lluvioso" }));
    panelCentro.add(comboPronostico);

    etiquetaTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaTemperatura.setText("Temperatura :");
    panelCentro.add(etiquetaTemperatura);

    comboTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calor", "Templado", "Frío" }));
    panelCentro.add(comboTemperatura);

    etiquetaHumedad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaHumedad.setText("Humedad :");
    panelCentro.add(etiquetaHumedad);

    comboHumedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Normal", "Baja" }));
    panelCentro.add(comboHumedad);

    etiquetaViento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaViento.setText("Viento :");
    panelCentro.add(etiquetaViento);

    comboViento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
    panelCentro.add(comboViento);

    etiquetaJugar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaJugar.setText("¿Jugará? ");
    panelCentro.add(etiquetaJugar);

    comboJugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
    panelCentro.add(comboJugar);

    getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

    botonAceptar.setText("Aceptar");
    panelSur.add(botonAceptar);

    botonCancelar.setText("Cancelar");
    panelSur.add(botonCancelar);

    getContentPane().add(panelSur, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonAceptar;
  private javax.swing.JButton botonCancelar;
  private javax.swing.JTextField campoNombre;
  private javax.swing.JComboBox<String> comboHumedad;
  private javax.swing.JComboBox<String> comboJugar;
  private javax.swing.JComboBox<String> comboPronostico;
  private javax.swing.JComboBox<String> comboTemperatura;
  private javax.swing.JComboBox<String> comboViento;
  private javax.swing.JLabel etiquetaHumedad;
  private javax.swing.JLabel etiquetaJugar;
  private javax.swing.JLabel etiquetaNombre;
  private javax.swing.JLabel etiquetaPronostico;
  private javax.swing.JLabel etiquetaTemperatura;
  private javax.swing.JLabel etiquetaViento;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelNorte;
  private javax.swing.JPanel panelSur;
  // End of variables declaration//GEN-END:variables
}
