/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controljugadores;

import java.awt.event.ActionListener;
import modelos.Jugadores;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class VentanaJugadores extends javax.swing.JFrame {

  /**
   * Creates new form VentanaJugadores
   */
  
  private Jugadores jugadores; // Modelo de datos
  
  public VentanaJugadores() {
    initComponents();
  }

  public VentanaJugadores(Jugadores jugadores) {
    this.jugadores = jugadores;
    initComponents();
    actualizarEtiquetas();
  }
  
  public void actualizarEtiquetas(){
    String archivo = jugadores.getNombreArchivo();
      archivo=archivo==null?"":archivo;
      this.etiquetaArchivo.setText("<html><b>Archivo: </b></html> "+archivo);
      this.etiquetaTotal.setText("<html><b>Total:</b></html> "+jugadores.getTotalJugadores());
      this.etiquetaJugar.setText("<html><b>Jugando:</b></html> "+jugadores.getTotalJugando());
  }
  
  public void addEventos(ActionListener oyente){
    this.opcionAbrir.addActionListener(oyente);
    this.opcionGuardar.addActionListener(oyente);
    this.opcionSalir.addActionListener(oyente);
    this.opcionRegistrar.addActionListener(oyente);
    this.opcionEditar.addActionListener(oyente);
    this.opcionEliminar.addActionListener(oyente);
    this.opcionInicializar.addActionListener(oyente);
    this.opcionAbrir.setName("abrir");
    this.opcionGuardar.setName("guardar");
    this.opcionSalir.setName("salir");
    this.opcionRegistrar.setName("registrar");
    this.opcionEditar.setName("editar");
    this.opcionEliminar.setName("eliminar");
    this.opcionInicializar.setName("inicializar");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    etiquetaTitulo = new javax.swing.JLabel();
    panelSur = new javax.swing.JPanel();
    etiquetaArchivo = new javax.swing.JLabel();
    etiquetaTotal = new javax.swing.JLabel();
    etiquetaJugar = new javax.swing.JLabel();
    panelCentro = new javax.swing.JScrollPane();
    tabla = new javax.swing.JTable();
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    opcionAbrir = new javax.swing.JMenuItem();
    opcionGuardar = new javax.swing.JMenuItem();
    separadorArchivo = new javax.swing.JPopupMenu.Separator();
    opcionSalir = new javax.swing.JMenuItem();
    menuOperaciones = new javax.swing.JMenu();
    opcionRegistrar = new javax.swing.JMenuItem();
    opcionEditar = new javax.swing.JMenuItem();
    opcionEliminar = new javax.swing.JMenuItem();
    separadorOperaciones = new javax.swing.JPopupMenu.Separator();
    opcionInicializar = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Control de jugadores");

    etiquetaTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
    etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiquetaTitulo.setText("Control de Jugadores");
    getContentPane().add(etiquetaTitulo, java.awt.BorderLayout.PAGE_START);

    panelSur.setLayout(new java.awt.GridLayout(1, 3));

    etiquetaArchivo.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
    etiquetaArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiquetaArchivo.setText("Archivo:");
    panelSur.add(etiquetaArchivo);

    etiquetaTotal.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
    etiquetaTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiquetaTotal.setText("Total:");
    panelSur.add(etiquetaTotal);

    etiquetaJugar.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
    etiquetaJugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiquetaJugar.setText("Jugando:");
    panelSur.add(etiquetaJugar);

    getContentPane().add(panelSur, java.awt.BorderLayout.SOUTH);

    panelCentro.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
    panelCentro.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

    tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    tabla.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Jugador", "Pronóstico", "Temperatura", "Humedad", "Viento", "Jugar"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tabla.setShowGrid(true);
    panelCentro.setViewportView(tabla);

    getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

    menuArchivo.setText("Archivo");

    opcionAbrir.setText("Abrir archivo");
    menuArchivo.add(opcionAbrir);

    opcionGuardar.setText("Guardar archivo");
    menuArchivo.add(opcionGuardar);
    menuArchivo.add(separadorArchivo);

    opcionSalir.setText("Salir");
    menuArchivo.add(opcionSalir);

    barraMenu.add(menuArchivo);

    menuOperaciones.setText("Operaciones");

    opcionRegistrar.setText("Registrar jugador");
    menuOperaciones.add(opcionRegistrar);

    opcionEditar.setText("Modificar jugador");
    menuOperaciones.add(opcionEditar);

    opcionEliminar.setText("Eliminar jugador");
    menuOperaciones.add(opcionEliminar);
    menuOperaciones.add(separadorOperaciones);

    opcionInicializar.setText("Inicializar tabla");
    menuOperaciones.add(opcionInicializar);

    barraMenu.add(menuOperaciones);

    setJMenuBar(barraMenu);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JLabel etiquetaArchivo;
  private javax.swing.JLabel etiquetaJugar;
  private javax.swing.JLabel etiquetaTitulo;
  private javax.swing.JLabel etiquetaTotal;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenu menuOperaciones;
  private javax.swing.JMenuItem opcionAbrir;
  private javax.swing.JMenuItem opcionEditar;
  private javax.swing.JMenuItem opcionEliminar;
  private javax.swing.JMenuItem opcionGuardar;
  private javax.swing.JMenuItem opcionInicializar;
  private javax.swing.JMenuItem opcionRegistrar;
  private javax.swing.JMenuItem opcionSalir;
  private javax.swing.JScrollPane panelCentro;
  private javax.swing.JPanel panelSur;
  private javax.swing.JPopupMenu.Separator separadorArchivo;
  private javax.swing.JPopupMenu.Separator separadorOperaciones;
  private javax.swing.JTable tabla;
  // End of variables declaration//GEN-END:variables
}
