/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesconherencia;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelPadre extends javax.swing.JPanel {

  /**
   * Creates new form PanelPadre
   */
  public PanelPadre() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    botonPadre = new javax.swing.JButton();

    setLayout(new java.awt.GridLayout(1, 3));

    botonPadre.setBackground(new java.awt.Color(7, 146, 7));
    botonPadre.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
    botonPadre.setText("¡Viva");
    add(botonPadre);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonPadre;
  // End of variables declaration//GEN-END:variables
}
