/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesconherencia;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelHijo extends PanelPadre {

  /**
   * Creates new form PanelHijo
   */
  public PanelHijo() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    botonHijo = new javax.swing.JButton();

    botonHijo.setBackground(new java.awt.Color(255, 255, 255));
    botonHijo.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
    botonHijo.setText("México");
    add(botonHijo);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonHijo;
  // End of variables declaration//GEN-END:variables
}
