/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesconherencia;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelNieto extends PanelHijo {

  /**
   * Creates new form PanelNieto
   */
  public PanelNieto() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNieto = new javax.swing.JButton();

    setFocusTraversalPolicyProvider(true);

    panelNieto.setBackground(new java.awt.Color(255, 17, 38));
    panelNieto.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
    panelNieto.setText("c...!");
    add(panelNieto);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton panelNieto;
  // End of variables declaration//GEN-END:variables
}
