/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package examene3;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelGrafica extends javax.swing.JPanel {

  /**
   * Creates new form PanelGrafica
   */
  public PanelGrafica() {
    initComponents();
  }
  
  @Override
  public void paintComponent(Graphics g){
    super.paintComponent(g);
    super.paintComponent(g);
        int ancho = this.getWidth();
        int alto = this.getHeight();
        g.translate(ancho / 2-20, alto / 2-20);
        int rExterior = 250;
        g.setColor(Color.YELLOW);
        g.fillOval(-rExterior, -rExterior, 2 * rExterior, 2 * rExterior);
        g.setColor(Color.BLACK);
        g.drawOval(-rExterior, -rExterior, 2 * rExterior, 2 * rExterior);
        // Arcos
        int rArcos = 230;
        //   g.fillArc(-rArcos, -rArcos, rArcos * 2, rArcos * 2, 0, 60);
        //   g.fillArc(-rArcos, -rArcos, rArcos * 2, rArcos * 2, 120, 60);
        //   g.fillArc(-rArcos, -rArcos, rArcos * 2, rArcos * 2, 240, 60);   
        int nArcos = 3;
        int factor = 360 / nArcos;
        for (int i = 0; i < nArcos; i++) {
          //g.fillArc(i, i, WIDTH, HEIGHT, factor, nArcos);
          //g.fill
            g.fillArc(-rArcos, -rArcos, rArcos * 2, rArcos * 2, factor * i, factor*2 );
        }
        int lados = 3;
        double angulo = 2*Math.PI/lados;
      int []x = new int[lados];
      int []y = new int[lados];
      for(int i=0;i<lados;i++){
        x[i]=(int)(radio*Math.cos(angulo*i));
        y[i]=(int)(radio*Math.sin(angulo*i));
      }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
