/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hiloscontadoresgrafico;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class PanelContador extends javax.swing.JPanel {

  /**
   * Creates new form PanelContador
   */
  public PanelContador() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    botonIniciar = new javax.swing.JButton();
    panelCentro = new javax.swing.JPanel();
    barra1 = new javax.swing.JSlider();
    barra2 = new javax.swing.JSlider();
    panelSur = new javax.swing.JPanel();
    etiqueta1 = new javax.swing.JLabel();
    etiqueta2 = new javax.swing.JLabel();

    setLayout(new java.awt.BorderLayout());

    botonIniciar.setText("Iniciar Contadores");
    panelNorte.add(botonIniciar);

    add(panelNorte, java.awt.BorderLayout.PAGE_START);

    panelCentro.setLayout(new java.awt.GridLayout(1, 2));

    barra1.setMajorTickSpacing(10);
    barra1.setOrientation(javax.swing.JSlider.VERTICAL);
    barra1.setPaintLabels(true);
    barra1.setPaintTicks(true);
    barra1.setValue(0);
    panelCentro.add(barra1);

    barra2.setMajorTickSpacing(10);
    barra2.setOrientation(javax.swing.JSlider.VERTICAL);
    barra2.setPaintLabels(true);
    barra2.setPaintTicks(true);
    barra2.setValue(0);
    panelCentro.add(barra2);

    add(panelCentro, java.awt.BorderLayout.CENTER);

    panelSur.setLayout(new java.awt.GridLayout(1, 2));

    etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta1.setText("Contador 1");
    panelSur.add(etiqueta1);

    etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta2.setText("Contador 2");
    panelSur.add(etiqueta2);

    add(panelSur, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JSlider barra1;
  private javax.swing.JSlider barra2;
  private javax.swing.JButton botonIniciar;
  private javax.swing.JLabel etiqueta1;
  private javax.swing.JLabel etiqueta2;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelNorte;
  private javax.swing.JPanel panelSur;
  // End of variables declaration//GEN-END:variables
}
