/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1;

import javax.swing.JTextField;

/**
 *
 * @author Kevin Alejandro Gutierrez Luna
 */
public class VentanaMonedas extends javax.swing.JFrame {

  /**
   * Creates new form VentanaMonedas
   */
  public VentanaMonedas() {
    initComponents();
  }
  
  public void addEventos(OyenteVentana oyente){
    this.campoCantidad.addActionListener(oyente);
  }

  public JTextField[] getCampos() {
    return new JTextField[]{campo1,campo2,campo5,campo10,campo20,campo50,campo100,campo200,campo500};
  }

  public JTextField getCampoCantidad() {
    return campoCantidad;
  }
  
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    eitiquetaCantidad = new javax.swing.JLabel();
    campoCantidad = new javax.swing.JTextField();
    panelCentro = new javax.swing.JPanel();
    denominacion1 = new javax.swing.JLabel();
    cantidad1 = new javax.swing.JLabel();
    denominacion2 = new javax.swing.JLabel();
    cantidad2 = new javax.swing.JLabel();
    eitiqueta500 = new javax.swing.JLabel();
    campo500 = new javax.swing.JTextField();
    etiqueta10 = new javax.swing.JLabel();
    campo10 = new javax.swing.JTextField();
    etiqueta200 = new javax.swing.JLabel();
    campo200 = new javax.swing.JTextField();
    etiqueta5 = new javax.swing.JLabel();
    campo5 = new javax.swing.JTextField();
    etiqueta100 = new javax.swing.JLabel();
    campo100 = new javax.swing.JTextField();
    etiqueta2 = new javax.swing.JLabel();
    campo2 = new javax.swing.JTextField();
    etiqueta50 = new javax.swing.JLabel();
    campo50 = new javax.swing.JTextField();
    etiqueta1 = new javax.swing.JLabel();
    campo1 = new javax.swing.JTextField();
    etiqueta20 = new javax.swing.JLabel();
    campo20 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Desglose de monedas y billetes");

    eitiquetaCantidad.setText("Cantidad:");
    panelNorte.add(eitiquetaCantidad);

    campoCantidad.setColumns(10);
    panelNorte.add(campoCantidad);

    getContentPane().add(panelNorte, java.awt.BorderLayout.PAGE_START);

    panelCentro.setLayout(new java.awt.GridLayout(6, 4));

    denominacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    denominacion1.setText("Denominación");
    panelCentro.add(denominacion1);

    cantidad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    cantidad1.setText("Cantidad");
    panelCentro.add(cantidad1);

    denominacion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    denominacion2.setText("Denominación");
    panelCentro.add(denominacion2);

    cantidad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    cantidad2.setText("Cantidad");
    panelCentro.add(cantidad2);

    eitiqueta500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    eitiqueta500.setText("500");
    panelCentro.add(eitiqueta500);

    campo500.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo500);

    etiqueta10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta10.setText("10");
    panelCentro.add(etiqueta10);

    campo10.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo10);

    etiqueta200.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta200.setText("200");
    panelCentro.add(etiqueta200);

    campo200.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo200);

    etiqueta5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta5.setText("5");
    panelCentro.add(etiqueta5);

    campo5.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo5);

    etiqueta100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta100.setText("100");
    panelCentro.add(etiqueta100);

    campo100.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo100);

    etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta2.setText("2");
    panelCentro.add(etiqueta2);

    campo2.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo2);

    etiqueta50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta50.setText("50");
    panelCentro.add(etiqueta50);

    campo50.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo50);

    etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta1.setText("1");
    panelCentro.add(etiqueta1);

    campo1.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo1);

    etiqueta20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiqueta20.setText("20");
    panelCentro.add(etiqueta20);

    campo20.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    panelCentro.add(campo20);

    getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField campo1;
  private javax.swing.JTextField campo10;
  private javax.swing.JTextField campo100;
  private javax.swing.JTextField campo2;
  private javax.swing.JTextField campo20;
  private javax.swing.JTextField campo200;
  private javax.swing.JTextField campo5;
  private javax.swing.JTextField campo50;
  private javax.swing.JTextField campo500;
  private javax.swing.JTextField campoCantidad;
  private javax.swing.JLabel cantidad1;
  private javax.swing.JLabel cantidad2;
  private javax.swing.JLabel denominacion1;
  private javax.swing.JLabel denominacion2;
  private javax.swing.JLabel eitiqueta500;
  private javax.swing.JLabel eitiquetaCantidad;
  private javax.swing.JLabel etiqueta1;
  private javax.swing.JLabel etiqueta10;
  private javax.swing.JLabel etiqueta100;
  private javax.swing.JLabel etiqueta2;
  private javax.swing.JLabel etiqueta20;
  private javax.swing.JLabel etiqueta200;
  private javax.swing.JLabel etiqueta5;
  private javax.swing.JLabel etiqueta50;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelNorte;
  // End of variables declaration//GEN-END:variables
}
